# Generated by Django 4.2.7 on 2023-11-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketHeader',
            fields=[
                ('basket_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('basket_saved', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('order_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.IntegerField()),
                ('order_text', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.orderheader')),
            ],
        ),
        migrations.AddField(
            model_name='orderheader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.user'),
        ),
        migrations.CreateModel(
            name='BasketLine',
            fields=[
                ('basket_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('line', models.IntegerField()),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.basketheader')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.material')),
            ],
        ),
    ]
