# Generated by Django 4.2.7 on 2023-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_basketline_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
