# Generated by Django 4.2.7 on 2023-12-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_basketheader_user_alter_orderheader_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketheader',
            name='user',
        ),
    ]
