# Generated by Django 4.2.7 on 2023-12-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0009_alter_basketheader_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date_added',
            field=models.DateField(default=datetime.date(2023, 11, 29)),
            preserve_default=False,
        ),
    ]
