# Generated by Django 5.0 on 2023-12-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0010_material_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='stock',
        ),
    ]
