# Generated by Django 5.0 on 2023-12-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0012_material_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(default='for sale', max_length=255),
            preserve_default=False,
        ),
    ]
