# Generated by Django 4.2.7 on 2024-01-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0013_material_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketline',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='basketline',
            name='order_text',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='order_text',
        ),
    ]
