# Generated by Django 4.2.7 on 2024-01-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0014_remove_basketline_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='amount',
        ),
    ]
